#!/usr/bin/env bash

set -ev

blt validate --no-interaction || { set +v && return 1; }
blt setup --define drush.alias='${drush.aliases.ci}' --no-interaction --verbose || { set +v && return 1; }
blt tests --define drush.alias='${drush.aliases.ci}' --define tests.run-server=true --no-interaction --verbose || { set +v && return 1; }

set +ev
