#!/usr/bin/env bash

set -ev

# Add composer bins to the PATH.
echo "$GITHUB_WORKSPACE/vendor/bin" >> $GITHUB_PATH

# Set git info.
git config --global user.name "Github"
git config --global user.email "noreply@github.com"

# Setup a local hostname.
echo "127.0.0.1 ci.davidpagini.com" | sudo tee -a /etc/hosts

# Verify that no git diffs (caused by line ending variation) exist.
# - git diff --exit-code

set +ev
