# Note that the example .travis.yml file for child projects lives in /install.
sudo: false
language: php
php:
  - '7.0'

before_install:
  - composer selfupdate
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
  # - mysql -e 'CREATE DATABASE drupal;'

install:
  # Load composer dependencies.
  - composer install
  - export PATH=$PATH:$TRAVIS_BUILD_DIR/vendor/bin

# Uncomment to enable automatic deployments following merges.
deploy:
  # provider: script
  # script: ./bolt.sh deploy:artifact -Ddeploy.commitMsg="Automated commit by Travis CI for Build ${TRAVIS_BUILD_ID}" -Ddeploy.branch="${TRAVIS_BRANCH}-build"
  # skip_cleanup: true
  # on:
  #   branch: master
