name: Pull request

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify & setup Lando
        run: |
          docker --version | grep "20.10."
          docker-compose --version | grep "1.29."
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-v3.6.4"
          sudo chmod +x /usr/local/bin/lando
          lando version

      - name: Build
        run: |
          lando start

      - name: Test
        run: |
          lando composer validate
          lando composer audit
          lando phpcs
          lando drush pm:security
