name: Publish

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify & setup Lando
        run: |
          docker --version | grep "20.10."
          docker-compose --version | grep "1.29."
          sudo curl -fsSL -o /usr/local/bin/lando "https://files.lando.dev/cli/lando-linux-x64-v3.6.4"
          sudo chmod +x /usr/local/bin/lando
          lando version

      - name: Build
        run: |
          lando start

      - name: Generate artifact
        run: |
          lando drush tome:static --uri=https://www.davidpagini.com
          mkdir ./_site && tar -czvf ./_site/github-pages.tar.gz ./html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.6
        with:
          path: "./html/"

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1.2.3
